services:
  - type: web
    name: mental-health-story
    env: node
    buildCommand: npm install && cd client && npm install && npm run build && cd ..
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        generateValue: false
      - key: GOOGLE_APPS_SCRIPT_URL
        sync: false
      - key: CORRECT_ANSWERS
        sync: false
